// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/risefit/email-worker/pkg/config"
	"github.com/risefit/email-worker/pkg/email"
	"github.com/risefit/email-worker/pkg/handler"
)

// Injectors from wire.go:

func InitializeServer() (*Server, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	provider := ProvideEmailProvider(configConfig)
	emailHandler := handler.NewEmailHandler(provider)
	server := &Server{
		Handler: emailHandler,
		Config:  configConfig,
	}
	return server, nil
}

// wire.go:

type Server struct {
	Handler *handler.EmailHandler
	Config  *config.Config
}

func ProvideEmailProvider(cfg *config.Config) email.Provider {
	return email.NewSendGridProvider(cfg.EmailProviderAPIKey, cfg.FromEmail)
}
